// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import RevealController from "./reveal_controller"
import TrixToolbarController from "./trix_toolbar_controller"

application.register("hello", HelloController)
application.register("reveal", RevealController)
application.register("trix-toolbar", TrixToolbarController)
